config/routes.rb
Rails.application.routes.draw do
  get 'search/results'
  # Route to Recipes
  resources :recipes, only: [:index, :show]

  # Route to Categories
  resources :categories, only: [:index, :show]

  # Manual Routes
  # Route to About Us
  get 'about', to: 'static_pages#about'

  # Search Results Action
  get 'search_results', to: 'search#results'

  # Setting Default Page
  root to: 'recipes#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :category_recipe, dependent: :destroy
  has_many :recipes, through: :category_recipe, dependent: :destroy

  validates :name, presence: true, uniqueness: true
end

app/models/category_recipe.rb
class CategoryRecipe < ApplicationRecord
  belongs_to :category
  belongs_to :recipe
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :ingredient_recipe, dependent: :destroy
  has_many :recipe, through: :ingredient_recipe, dependent: :destroy

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/ingredient_recipe.rb
class IngredientRecipe < ApplicationRecord
  belongs_to :ingredient
  belongs_to :recipe

  validates :count, presence: true, numericality: {only_integers: true}
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :category_recipe, dependent: :destroy
  has_many :category, through: :category_recipe, dependent: :destroy
  has_many :ingredient_recipe, dependent: :destroy
  has_many :ingredient, through: :ingredient_recipe, dependent: :destroy

  validates :name, :instructions, :calories, :image, presence: true
  validates :calories, numericality: {only_integers: true}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def go_to_root
    flash[:notice] = 'Page not found. Redirecting to the homepage.'
    redirect_to root_path
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @categories = Category.order(:name)
  end

  def show
    @category = Category.find(params[:id])
    @recipes = @category.recipes
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.includes(:category, :ingredient).order(:name).page(params[:page]).per(10)
  end

  def show
    @recipe = Recipe.includes(:category, :ingredient, :ingredient_recipe).find(params[:id])
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def results
    # Getting Access to User Submitted Query
    @query = params[:q]

    # Filter by category if :category parameter is present
    if params[:category].present?
      @category = Category.find(params[:category])
      @recipes = @category.recipes.where('name LIKE ?', "%#{@query}%").page(params[:page]).per(10)
    else
      @recipes = Recipe.where('name LIKE ?', "%#{@query}%").page(params[:page]).per(10)
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/categories/index.html.erb
<h2>All Categories</h2>

<ul>
  <% @categories.each do |category| %>
    <li><%= link_to category.name, category %></li>
  <% end %>
</ul>

app/views/categories/show.html.erb
<h2>Recipes Under Category: <%= @category.name %></h2>

<ul>
  <% @recipes.each do |recipe| %>
    <li><%= link_to recipe.name, recipe %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <title>RecipeProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="bg-primary text-white">
           <div class="container">
        <h1 class="mb-4">Recipe Recipe</h1>
        <nav>
          <ul class="list-unstyled list-inline center-bold">
            <li class="list-inline-item"><%= link_to "Home", root_path, class: "text-white" %></li>
            <li class="list-inline-item"><%= link_to "Categories", categories_path, class: "text-white" %></li>
            <li class="list-inline-item"><%= link_to "About Us", about_path, class: "text-white" %></li>
          </ul>
        </nav>
      </div>
    </header>

    <div class="searchbar bg-light p-3">
      <div class="container">
        <%= form_tag(search_results_path, method: "get") do %>
          <div class="form-group mb-3">
            <%= label_tag(:q, "Search for:", class: "font-weight-bold") %>
            <%= text_field_tag(:q, params[:q], class: "form-control") %>
          </div>
          <div class="form-group mb-3">
            <%= label_tag(:category, "Filter by Category:", class: "font-weight-bold") %>
            <%= select_tag(:category, options_for_select(Category.all.collect { |c| [c.name, c.id] }, params[:category]), include_blank: true, class: "form-control") %>
          </div>
          <%= submit_tag("Search", class: "btn btn-primary") %>
        <% end %>
      </div>
    </div>
<div class="container">

    <%= yield %>


</div>
  </body>
</html>

app/views/recipes/_recipe.html.erb
    <div class="col-md-3">
      <div class="row">
        <p class="d-flex align-items-center "><%= link_to recipe.name, recipe %></p>
        <img src="<%= recipe.image %>" width="200" height="200" alt="<%= recipe.name %>">
      </div>
    </div>

app/views/recipes/index.html.erb
  <%= stylesheet_link_tag 'application', media: 'all' %>


  <h2>All Recipes</h2>
  <div class="recipe-grid">
    <%= render @recipes %>
  </div>
  <div class="pagination">
    <%= paginate @recipes %>
  </div>

app/views/recipes/show.html.erb
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= stylesheet_link_tag 'recipe', media: 'all' %> <!-- Add this line to include the recipe.css file -->


  <div class="container">
    <h1><%= @recipe.name %></h1>

    <p class="description">Description: <%= @recipe.description %></p>
    <img src="<%= @recipe.image %>" width="500" height="500" alt="<%=@recipe.name%>">

    <p class="category-title">Category:</p>
    <ul class="categories">
      <% @recipe.category.each do |c| %>
        <li><%= link_to c.name, category_path(c) %></li>
      <% end %>
    </ul>

    <p class="ingredients-title">Ingredients:</p>
    <ul class="ingredients">
      <% @recipe.ingredient.each do |ingredient| %>
    <li><%= "#{ingredient.ingredient_recipe.find_by(recipe_id: @recipe.id).count} #{ingredient.name}" %></li>
  <% end %>
    </ul>

    <p class="instructions-title">Instructions:</p>
    <p class="instructions"><%= @recipe.instructions %></p>
  </div>

app/views/search/results.html.erb
<h3>
  <% if @query.present? && @category.present? %>
      Your query of "<%= @query %>" and category "<%= @category.name %>" have returned <%= pluralize(@recipes.count, 'result') %>.
    <% elsif @query.present? %>
      Your query of "<%= @query %>" has returned <%= pluralize(@recipes.count, 'result') %>.
    <% elsif @category.present? %>
      Recipes in category "<%= @category.name %>" have been returned.
    <% else %>
      No search criteria provided. Showing all recipes.
    <% end %>
</h3>

<div class="recipe-grid">
  <%= render @recipes %>
</div>

<div class="pagination">
  <%= paginate @recipes %>
</div>

app/views/static_pages/about.html.erb
<h1 class="text-center my-4">Welcome to the About Us</h1>

<div class="d-flex justify-content-center">
  <%= image_tag "ERD.png", height: 300, alt: "ERD" %>
</div>

<div class="d-flex justify-content-center mt-3">
  <%= image_tag "recipeIngredients.png", height: 300, alt: "CSV" %>
</div>

<div class="text-center mt-3">
  <h6>Web scraped data from allrecipes.com put into a CSV file.</h6>
</div>

<div class="text-center mt-3">
  <p>We used Faker for the count of the individual ingredients and calories.</p>
</div>